
services:
  dev-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kid123gemaw
      - POSTGRES_DB=chat_app
    networks:
      - freecodecamp


  test-db:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kid123gemaw
      - POSTGRES_DB=chat_app
    networks:
      - freecodecamp

networks:
  freecodecamp:
         